### ISSUE TITLE
Add handy to open source directory

### ISSUE THREAD

**Issue by diegomacario** [Shopify/shopify.github.com#111]
The Spatial Commerce team created a tool called `Handy` that can be used to mocap hands using a Meta Quest headset.

This is Handy's repo: https://github.com/Shopify/handy

We have open sourced it because it's useful for 3D artists, and because it helps us promote Shopify engineering.

We would like it to be added to Shopify's open source directory.

We will be promoting the repo next week on Twitter.

Thank you!

**Comment by rafaelfranca** [comment]
Can you please open a PR?

**Comment by diegomacario** [comment]
Sure, here is the PR: https://github.com/Shopify/shopify.github.com/pull/114
