### ISSUE TITLE
Unprocessed filters in documentation

### ISSUE THREAD

**Issue by noscript** [Shopify/shopify.github.com#46]
Scroll to the end on https://shopify.github.io/liquid/filters/ and see:
```
Input
{% raw %}
{{ "john@liquid.com" | url_encode }}
{% endraw %}

Output
{{ "john@liquid.com" | url_encode }}

Input
{% raw %}
{{ "Tetsuro Takara" | url_encode }}
{% endraw %}

Output
{{ "Tetsuro Takara" | url_encode }}
```
Output is same as input.

Then go the the filter sub page https://shopify.github.io/liquid/filters/url_encode/:
```
Input
{{ "john@liquid.com" | url_encode }}

Output
john%40liquid.com

Input
{{ "Tetsuro Takara" | url_encode }}

Output
Tetsuro+Takara
```

**Comment by cshold** [comment]
Mind adding this to the appropriate repo at https://github.com/Shopify/shopify.github.com/issues/46

This repo is just for the landing page at http://shopify.github.io/
