### ISSUE TITLE
add a new project to Shopify open source

### ISSUE THREAD

**Issue by ghost** [Shopify/shopify.github.com#67]
The partner team wants to add the following project repo:

https://github.com/MLH/mlh-localhost-shopify-graphql
 
to the Shopify open source page listing:

https://shopify.github.io/

Legal has approved cloning/copying  this repo.

**Comment by sharath2106** [comment]
I would like to work on this issue.

**Comment by kaelig** [comment]
Closing this, as the project in this issue isn't directly affiliated with Shopify.
