### ISSUE TITLE
Fraud IP Throttle on CAD Hardware Store declining new orders

### ISSUE THREAD

**Issue by slaposta** [Shopify/shopify.github.com#86]
First time posting an issue here.
Couple of instances where a merchant is attempting to place an order, was flagged fraud due to IP Throttle and all subsequent orders from merchant are being declined with reason noting "zip code failure".  Merchant has tried multiple cards and is unable to place the order.

@lucasuyezu asked to open an issue here based on this slack thread:  https://shopify.slack.com/archives/C7PDEEPRV/p1602261361365000

![](https://screenshot.click/20-10-lf7yw-wke5o.png)

![](https://screenshot.click/20-10-vootr-8ut8z.png)

**Comment by lucasuyezu** [comment]
Let's move this over to `Shopify/shopify`

**Comment by lucasuyezu** [comment]
Closing this in favour of https://github.com/Shopify/shopify/issues/264274
